export const FETCH_ALL_TEETIMES_PENDING = "FETCH_ALL_TEETIMES_PENDING";
export const FETCH_ALL_TEETIMES_FAILED = "FETCH_ALL_TEETIMES_FAILED";
export const FETCH_ALL_TEETIMES_SUCCESS = "FETCH_ALL_TEETIMES_SUCCESS";

export const FETCH_ONE_TEETIME_PENDING = "FETCH_ONE_TEETIME_PENDING";
export const FETCH_ONE_TEETIME_FAILED = "FETCH_ONE_TEETIME_FAILED";
export const FETCH_ONE_TEETIME_SUCCESS = "FETCH_ONE_TEETIME_SUCCESS";

export const ADD_TEETIME_PENDING = "ADD_TEETIME_PENDING";
export const ADD_TEETIME_SUCCESS = "ADD_TEETIME_SUCCESS";
export const ADD_TEETIME_FAILED = "ADD_TEETIME_FAILED";

export const REMOVE_TEETIME_PENDING = "REMOVE_TEETIME_PENDING";
export const REMOVE_TEETIME_SUCCESS = "REMOVE_TEETIME_SUCCESS";
export const REMOVE_TEETIME_FAILED = "REMOVE_TEETIME_FAILED";

export const UPDATE_TEETIME_PENDING = "UPDATE_TEETIME_PENDING";
export const UPDATE_TEETIME_SUCCESS = "UPDATE_TEETIME_SUCCESS";
export const UPDATE_TEETIME_FAILED = "UPDATE_TEETIME_FAILED";

export const BASE_URL = "http://localhost:8000/teetimes";
