export const FETCH_ALL_CUSTOMERS_PENDING = "FETCH_ALL_CUSTOMERS_PENDING";
export const FETCH_ALL_CUSTOMERS_FAILED = "FETCH_ALL_CUSTOMERS_FAILED";
export const FETCH_ALL_CUSTOMERS_SUCCESS = "FETCH_ALL_CUSTOMERS_SUCCESS";

export const FETCH_ONE_CUSTOMER_PENDING = "FETCH_ONE_CUSTOMER_PENDING";
export const FETCH_ONE_CUSTOMER_FAILED = "FETCH_ONE_CUSTOMER_FAILED";
export const FETCH_ONE_CUSTOMER_SUCCESS = "FETCH_ONE_CUSTOMER_SUCCESS";

export const ADD_CUSTOMER_PENDING = "ADD_CUSTOMER_PENDING";
export const ADD_CUSTOMER_SUCCESS = "ADD_CUSTOMER_SUCCESS";
export const ADD_CUSTOMER_FAILED = "ADD_CUSTOMER_FAILED";

export const REMOVE_CUSTOMER_PENDING = "REMOVE_CUSTOMER_PENDING";
export const REMOVE_CUSTOMER_SUCCESS = "REMOVE_CUSTOMER_SUCCESS";
export const REMOVE_CUSTOMER_FAILED = "REMOVE_CUSTOMER_FAILED";

export const UPDATE_CUSTOMER_PENDING = "UPDATE_CUSTOMER_PENDING";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_FAILED = "UPDATE_CUSTOMER_FAILED";

export const BASE_URL = "http://localhost:8000/customers";
